add_newline = true

format = """$time$directory$git_branch$git_commit$python$status
$character
"""

[directory]
truncation_length = 3
truncation_symbol = '(â€¦)/'
truncate_to_repo = false
format = "ğŸ“[$path]($style)[$read_only]($read_only_style) "
home_symbol = '~'

[status]
symbol = "ğŸ”´"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[time]
disabled = false
format="ğŸ•°  [$time]($style) "
time_format = "%R"
